name: CI/CD Pipeline to GitHub Pages

# This workflow is triggered on every push to the "main" branch
on:
  push:
    branches: [ "main" ]

# We are giving the workflow permission to write to the repository (needed for deployment)
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job 1: Build and Test (this is the "CI" or Continuous Integration part)
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          # This is a simple 'test'. It checks if the file exists and is valid.
          if [ ! -f "index.html" ]; then
            echo "Error: index.html file not found!"
            exit 1
          else
            echo "✓ index.html found. Basic validation passed."
          fi

  # Job 2: Deploy (this is the "CD" or Continuous Deployment part)
  deploy:
    # This job only runs if the build-and-test job was successful
    needs: build-and-test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
